### ISSUE TITLE
Implement superpixel based tracking 

### ISSUE THREAD

**Issue by tsoonjin** [jinified/visionx#12]
- [ ] implement visual attention algorithm using different color space 
- [ ] set weight preference for non-bluish region 
- [ ] use scikit learn superpixel to give (L,a,b,x,y)
- [ ] calculate SSD to get next FOA
